baseURL = "https://www.flyinggrizzly.net/games/against-the-titans-of-war/"
publishDir = "public/against-the-titans-of-war"
canonifyUrls = true

disableKinds = ["taxonomy", "taxonomyTerm"]

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Against the Titans of War"
theme = "docuapi"
themesdir = "./themes"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[params]
  description = "A game about drawing former enemies and allies together to resist a corrupt oppressor"
  author = "Sean DMR <sean@flyinggrizzly.net>"
  themeVariant = "msitb" # choose theme variant "green", "gold" , "gray", "blue" (default)
  showVisitedLinks = true
  disableSearch = false
  disableShortcutsTitle = true
  disableBreadcrumb = true
  disableNextPrev = true
  ordersectionsby = "weight" # ordersectionsby = "title"
  editURL = "https://github.com/flyinggrizzly/mobile-suits-in-the-black/edit/release/content/"
  disableAssetsBusting = false
  disableInlineCopyToClipBoard = false
  enableGitInfo = true
  search = true

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> Github repo"
  url = "https://github.com/flyinggrizzly/mobile-suits-in-the-black"
  weight = 10
