baseURL = "https://www.flyinggrizzly.net/games/against-the-titans-of-war/"
publishDir = "public/against-the-titans-of-war"
canonifyUrls = true

disableKinds = ["taxonomy", "taxonomyTerm"]

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "Against the Titans of War"
theme = "docuapi"
themesdir = "./themes"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false

[params]
  description = "A game about drawing former enemies and allies together to resist a corrupt oppressor"
  author = "Sean DMR <sean@flyinggrizzly.net>"
  search = true

[languages.en]
  toc_footers = [
    '<a class="books-menu-footer" href="https://www.flyinggrizzly.net/"><img src="/images/white-flying-grizzly.png" />Run home Jack</a>'
  ]
